call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
let g:coc_disable_startup_warning = 1

" 十字光标
:set cursorline cursorcolumn


" 解决报错（无法打开交换文件）
 set directory=.,$TEMP

" 解决插入模式下delete/backspce键失效问题
set backspace=2

"状态栏
set laststatus=2

" 显示中文帮助
if version >= 603
	    set helplang=cn
	        set encoding=utf-8
	endif
" 设置鼠标可用
" set mouse=a
" 显示行号
set number
" Tab 键的宽度
set tabstop=4
" 统一缩进为 4
set softtabstop=4
set shiftwidth=4
" 不要使用 vi 的键盘模式，而是 vim 自己的
set nocompatible
" 语法高亮
set bg=dark
"set syntax=on
 "Ctrl-A 选中所有内容
map <silent>  <C-A>  gg v G 
"按TAB键时命令行自动补齐"
set wildmenu
"开启文件类型检查
filetype indent on

set showmatch
"光标遇到圆括号、方括号、大括号时，自动高亮对应的另一个圆括号、方括号和大括号
set spell spelllang=en_us
"打开英语单词的拼写检查
set history=1000
"Vim 需要记住多少次历史操作
set autoread
"打开文件监视。如果在编辑过程中文件发生外部改变（比如被别的编辑器编辑了），就会发出提示

colorscheme elflord
"设置主题配色

" 系统剪贴板
" set clipboard=unnamed

" WSL yank support
" let s:clip = '/mnt/c/Windows/System32/clip.exe'  " change this path according to your mount point
"if executable(s:clip)
 "   augroup WSLYank
  "      autocmd!
   "     autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
   " augroup END
" endif



"set paste
set pastetoggle=<F9>




